DROP TABLE IF EXISTS `user`;

CREATE TABLE `users` (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    birth_date DATE,
    contact VARCHAR(100) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL
);
